### ISSUE TITLE
Unable to get UART working..

### ISSUE THREAD

**Issue by i5Js** [gisab/WDMC-Ex2#3] opened 2022-11-06 04:30 UTC
Hi!

I have a WD EX2 Ultra, and I need your  help.

I’ve solder the uart interface but it doesn’t work. I don’t know why, but I don’t get anything when the nas boot up. I press space, 1, all the combinations available,but nothing works. I have tested the connections several times, and it seem they are fine. WIth a multi tester I see there is connectivity between the two sides, and I don’t know what else I can do to fix or figure out what is going on here. 

After one week, troubleshooting with @bodhi in this thread https://forum.doozan.com/read.php?2,132015,133249,page=3#msg-133249, and seeing that it’s imposible that the WD boot with the new kernel and the ram disk without the u-boot updated, I need a dump of that partition ( /devmtd0) to flash my hand. 

Could you please dump your u-boot partition? I guess it could the only chance I have to upgrade the WD to the new kernel.

Many thanks in advanced,

**Comment by gisab** [comment] 2022-11-06 06:55
Hi. 
Let’s be calm and analyze the situation. 
The “1” shall work :)

Let’s recheck the steps:
Are you able to see the Uboot log messages via the serial cable?
Which program do you use to communicate on the serial? Can you describe your setup?
If the RX is fine but the TX not… it can only be the TX wire. 
Do you keep the “1” pressed since you power on the nas?

**Comment by gisab** [comment] 2022-11-06 07:06
Can you send photos of the cable setup?
Have you connected the RX->TX and TX->RX?

**Comment by i5Js** [comment] 2022-11-06 07:13
Hey Gisab, 

Many thanks, of course , I would like to get it working, but I don’t know what else I can do. 

Answering your questions: I can’t see anything, but anything, nothing… it’s very frustrating, but it’s true.  I have used OS X , windows, Linux and a Raspberry. I’ve used screen in OS X, Linux, putty in windows and Serial in OS X too, but nothing. I have tested the device it self, connecting RX to TX and I can see what I am typing.

I have pressed 1, space, esc, and all the keys :) My device has a led when you send something, and it’s blinking when I press a key, so I guess RX is working. 

I have tested the cables in all the positions: RX-RX, TX-TX and RX-TX, TX-RX but same.

I will send some pictures later on.

Even, I’ve restored the stock firmware, thinking that perhaps the UART was disabled, but of course, it didn’t work, and I can’t come back debian stretch and Kernel 4.x hahahah.. a mess!

Anything else?

Again, many thanks for helping me.

**Comment by gisab** [comment] 2022-11-06 07:41
Ok. So the problem is on how did you connect the serial. 

The serial is not disabled on nas side.

The serial device have leds; true. These are electric and not sw driven. This means that when the nas (connected to your RX pin) transmit a signal, the RX led is blinking. 
When you send something from your device, the TX led will blink. 

The leds exist to debug exactly this part of the connection : )))

Once you have the RX led blinking during the boot, this means that the nas is really sending something which is received by your device. Then it’s the time to debug the SW configuration on your serial sw (baud, protocol, …)

**Comment by gisab** [comment] 2022-11-06 07:42
Note that nas is sending data ONLY during the boot sequence.

**Comment by i5Js** [comment] 2022-11-06 07:50
Ok, understood, so the issue is the RX, because it has no led anytime. I made a mistake and reading your post, tx is the led blinking when I press a key. I will try to send u the pics now.

**Comment by i5Js** [comment] 2022-11-06 07:58
Ah, about the connection 115200,8,n,1 with and without flow control

**Comment by i5Js** [comment] 2022-11-06 09:19
I've created a temporary one, check it here

https://github.com/i5Js/WD-EX2-Ultra/tree/main

**Comment by gisab** [comment] 2022-11-06 09:49
It seems that the comments allow to attach photo. Strange. 
Please upload the photo somewhere on internet (even in a temporary github project) and share the link.

**Comment by gisab** [comment] 2022-11-06 10:55
Hi i5JS.
We have checked that the wiring was wrong.
I'm closing the issue.

**Comment by gisab** [comment] 2022-11-06 10:56
Hi i5JS.
We have checked that the wiring was wrong.
I'm closing the issue.

**Closed by gisab** 2022-11-06 10:56 UTC
